[package]
name = "knobs"
version = "0.5.0"
edition = "2021"
homepage = "https://github.com/ecks0/knobs"
license = "MIT"
authors = ["eckso <eckso@eckso.io>"]

[dependencies]
async-trait = "0.1.52"
clap = "~2.33"
#clap = "~3.0"
comfy-table = "~5.0"
env_logger = "~0.9"
futures = "0.3.19"
log = "~0.4"
measurements = "~0.10"
nix = "~0.23"
num = "0.4.0"
regex = "~1.5"
#syx = { git = "https://github.com/ecks0/syx", features = ["logging"] }
syx = { path = "/home/user/src/syx", features = ["logging"] }
thiserror = "~1.0"

[dependencies.tokio]
version = "~1.14"
default-features = false
features = [
  "io-std",
  "io-util",
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
]
