[package]
name = "knobs"
version = "0.5.1"
edition = "2021"
homepage = "https://github.com/ecks0/knobs"
license = "MIT"
authors = ["eckso <eckso@eckso.io>"]

[dependencies]
async-trait = "~0.1"
clap = "~2.34"
comfy-table = "~5.0"
env_logger = "~0.9"
futures = "~0.3"
log = "~0.4"
measurements = "~0.10"
nix = "~0.23"
num = "~0.4"
regex = "~1.5"
syx = { git = "https://github.com/ecks0/syx", features = ["nvml"] }
thiserror = "~1.0"

[dependencies.tokio]
version = "~1.15"
default-features = false
features = [
  "io-std",
  "io-util",
  "macros",
  "parking_lot",
  "rt-multi-thread",
  "sync",
  "time",
]
