[package]
name = "knobs"
version = "0.4.0"
edition = "2021"
homepage = "https://github.com/ecks0/knobs"
license = "MIT"
authors = ["eckso <eckso@eckso.io>"]

[features]
default = ["nvml", "cli"]
nvml = ["nvml-wrapper"]
cli = ["clap", "comfy-table", "env_logger", "measurements", "regex", "serde_yaml"]

[dependencies]
async-trait = "0.1"
clap = { version = "2.33", optional = true }
comfy-table = { version = "4.1", optional = true }
dirs = "4.0.0"
env_logger = { version = "0.9", optional = true }
log = "0.4"
measurements = { version = "0.10", optional = true }
nix = "0.23"
nvml-wrapper = { version = "0.7", optional = true }
regex = { version = "1.5", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.8", optional = true }
thiserror = "1"

[dependencies.tokio]
version = "1.12"
default-features = false
features = [
  "fs",
  "io-std",
  "io-util",
  "rt",
  "rt-multi-thread",
  "sync",
  "parking_lot",
  "time",
  "macros",
]
