[package]
name = "knobs"
version = "0.4.0"
edition = "2021"
homepage = "https://github.com/ecks0/knobs"
license = "MIT"
authors = ["eckso <eckso@eckso.io>"]

[features]
default = []
nvml = ["nvml-wrapper"]

[dependencies]
async-trait = "0.1"
clap = "2.33"
comfy-table = "4.1"
dirs = "4.0.0"
env_logger = "0.9"
log = "0.4"
measurements = { version = "0.10" }
nix = "0.23"
nvml-wrapper = { version = "0.7", optional = true }
once_cell = "1.8.0"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
thiserror = "1"

[dependencies.tokio]
version = "1.12"
default-features = false
features = [
  "fs",
  "io-std",
  "io-util",
  "rt",
  "rt-multi-thread",
  "sync",
  "parking_lot",
  "time",
  "macros",
]
