[package]
name = "knobs"
version = "0.2.0"
edition = "2018"

[dependencies]
clap = "2.33"
measurements = "0.10"
tabular = "0.1"
thiserror = "1"
zysfs = { git = "https://github.com/ecks0/zysfs-rs", features = ["blocking", "types"] }
