[package]
name = "knobs"
version = "0.4.1"
edition = "2021"
homepage = "https://github.com/ecks0/knobs"
license = "MIT"
authors = ["eckso <eckso@eckso.io>"]

[features]
default = []
cli = [
  "clap",
  "comfy-table",
  "dirs",
  "env_logger",
  "measurements",
  "regex",
  "serde",
  "serde_yaml",
  "tokio/io-std",
  "tokio/io-util",
  "tokio/macros",
  "tokio/rt-multi-thread",
]
nvml = [
  "nvml-wrapper",
]

[dependencies]
async-trait = "~0.1"
clap = { version = "~2.33", optional = true }
comfy-table = { version = "~5.0", optional = true }
dirs = { version = "~4.0", optional = true }
env_logger = { version = "~0.9", optional = true }
log = "~0.4"
measurements = { version = "~0.10", optional = true }
nix = "~0.23"
nvml-wrapper = { version = "~0.7", optional = true }
regex = { version = "~1.5", optional = true }
serde = { version = "~1.0", features = ["derive"], optional = true }
serde_yaml = { version = "~0.8", optional = true }
thiserror = "~1.0"

[dependencies.tokio]
version = "~1.14"
default-features = false
features = [
  "fs",
  "rt",
  "parking_lot",
  "sync",
  "time",
]
