edition = "2021"
version = "Two"

chain_width = 90
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
inline_attribute_width = 50
match_block_trailing_comma = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
single_line_if_else_max_width = 99
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
